spring:
  security:
    oauth2:
      client:
        registration:
          instagram:
            client-id: 1121361469184221
            client-secret: 3f1c0ec4bf741db8a5a5587464e3384f
            redirect-uri: https://localhost:8080
            scope: ["instagram_basic", "instagram_graph_user_profile", "instagram_graph_user_media"]
            authorization-grant-type: authorization_code
            client-authentication-method: post
        provider:
          instagram:
            authorization-uri: https://www.facebook.com/v10.0/dialog/oauth
            token-uri: https://graph.instagram.com/access_token
            user-info-uri: https://graph.instagram.com/me

  elasticsearch:
    uris: http://localhost:9200