spring:
  security:
    oauth2:
      client:
        registration:
          instagram:
            client-id: <YOUR_META_APP_NAME>
            client-secret: <YOUR_META_APP_SECRET>
            redirect-uri: <YOUR_REDIRECT_URI>
            scope: ["instagram_basic", "instagram_graph_user_profile", "instagram_graph_user_media"]
            authorization-grant-type: authorization_code
            client-authentication-method: post
        provider:
          instagram:
            authorization-uri: https://www.facebook.com/v10.0/dialog/oauth
            token-uri: https://graph.instagram.com/access_token
            user-info-uri: https://graph.instagram.com/me

  elasticsearch:
    uris: http://localhost:9200
    username: guest
    password: 123@abc