version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb_container
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: smat
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - mariadb_network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_USERNAME=guest
      - ELASTIC_PASSWORD=nopasswordhere
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - mariadb_network

  echo-post-backend:
    container_name: echo_post_backend
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - ES_HOST=${ES_HOST}
      - ES_PORT=${ES_PORT}
      - INSTAGRAM_CLIENT_ID='asdfasdfasfasd'
      - INSTAGRAM_CLIENT_SECRET="asdfasfasdf"
      - INSTAGRAM_REDIRECT_URI="asdfasdfasdfasfsdf"
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
      - elasticsearch
    networks:
      - mariadb_network
volumes:
  mariadb_data:
    driver: local
  elasticsearch_data:
    driver: local

networks:
  mariadb_network:
    driver: bridge
